# Generated by Django 5.2 on 2025-06-01 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='reminder_time',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_reminder_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='reminder_interval',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
