# Generated by Django 5.2 on 2025-06-01 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_remove_userprofile_reminder_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='daily_goal',
            field=models.PositiveIntegerField(default=2000),
        ),
    ]
