# Generated by Django 5.2 on 2025-06-22 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_userprofile_mobile_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='mobile_no',
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
    ]
