# Generated by Django 5.2 on 2025-06-22 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_alter_userprofile_mobile_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='mobile_no',
        ),
    ]
